[commands.start]
name = "start"
message = "Привет! Чтобы продолжить выберите категорию необходимой услуги ниже!"

[buttons.beats]
name = "Биты"
message = """
Для приобретения бита пришлите название и вид услуги нашей команде

 1. https://t.me/e_n_d_official
 2. https://t.me/DED_V_Groby
 3. https://t.me/chernobaevsky
 """
use_keyboard = true
image = "beats.jpg"

[buttons.button2]
name = "Дизайн"
message = """
Для приобретения услуг по дизайну пришлите название товара нашей команде

 1. https://t.me/onesevenx
 2. https://t.me/chernobaevsky
"""
use_keyboard = true
image = "covers.jpg"

[buttons.button3]
name = "Видео"
message = """
Для покупки видео услуг пришлите название товара нашей команде

 1. https://t.me/onesevenx
 2. https://t.me/chernobaevsky
"""
image = "motion.jpg"
use_keyboard = true

[messages]
command_error = "Извините, данной команды нет, все команды доступны по кнопкам ниже"